const { VITE_LUCID_BLOB_ADDRESS, VITE_WALLET_CONNECT_PROJECT_ID } = import.meta.env

const LUCID_BLOB_ADDRESS = VITE_LUCID_BLOB_ADDRESS
const WALLET_CONNECT_PROJECT_ID = VITE_WALLET_CONNECT_PROJECT_ID

export { LUCID_BLOB_ADDRESS, WALLET_CONNECT_PROJECT_ID }
